:toc:
:toc-placement!:

= ThreescaleApicastLatencyHigh

toc::[]

== Description

* This alert will trigger if the `apicast-staging`/`apicast-production` **p99** latency is greater than a given threshold
* Latency metric includes the time the request spent in apicast plus the time it took the upstream to respond

== Troubleshooting

* Check if `apicast-staging`/`apicast-production` pods might not be able to deal with incoming traffic due to high CPU usage
- You may need to consider scaling horinzontally `apicast-staging`/`apicast-production` deployment
- You may need to consider increasing `apicast-staging`/`apicast-production` deployment resources requests/limits
* Check if upstream response is taking too much time
* Check if the current traffic is normal based on the historical data. An unexpected change in the traffic pattern can be legit, and will require scaling up, but it also can be due to an abnormal or malicious traffic

== Verification

* Alert should disappear once the `apicast-staging`/`apicast-production` **p99** latency is below the threshold
